# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 16:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionesPeliculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_MovieAPI', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=60)),
                ('img_portada', models.CharField(max_length=300)),
                ('pendiente', models.BooleanField()),
                ('vista', models.BooleanField()),
                ('favorita', models.BooleanField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccionesPersonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_PersonAPI', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=60)),
                ('img_perfil', models.CharField(max_length=300)),
                ('favorita', models.BooleanField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccionesSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_SerieAPI', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=60)),
                ('img_portada', models.CharField(max_length=300)),
                ('pendiente', models.BooleanField()),
                ('vista', models.BooleanField()),
                ('favorita', models.BooleanField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=150)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('media', models.CharField(choices=[('Pel\xedculas', 'Pel\xedculas'), ('Series', 'Series')], default=0, max_length=10)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contentAPI', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=60)),
                ('img_portada', models.CharField(max_length=300)),
                ('id_coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxfilm.Colecciones')),
            ],
        ),
    ]
