# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contenidoAPI', models.IntegerField(unique=True)),
                ('titulo', models.TextField(max_length=100)),
                ('img_contenido', models.CharField(max_length=400)),
                ('pendiente', models.BooleanField()),
                ('vista', models.BooleanField()),
                ('recomendar', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Colecciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100)),
                ('mensaje', models.TextField(max_length=300)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_contenidoAPI', models.IntegerField(unique=True)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contenidoAPI', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=40)),
                ('img_contenido', models.CharField(max_length=400)),
                ('id_coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxfilm.Colecciones')),
            ],
        ),
        migrations.CreateModel(
            name='MensajesTablon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=250)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=60)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(upload_to='imgPerfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mensajestablon',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxfilm.Usuarios'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxfilm.Usuarios'),
        ),
        migrations.AddField(
            model_name='colecciones',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxfilm.Usuarios'),
        ),
        migrations.AddField(
            model_name='acciones',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxfilm.Usuarios'),
        ),
    ]
