# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxfilm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccionesPeliculas',
            new_name='AccionPelicula',
        ),
        migrations.RenameModel(
            old_name='AccionesPersonas',
            new_name='AccionPersona',
        ),
        migrations.RenameModel(
            old_name='AccionesSeries',
            new_name='AccionSerie',
        ),
        migrations.RenameModel(
            old_name='Colecciones',
            new_name='Coleccion',
        ),
        migrations.AlterModelOptions(
            name='accionpelicula',
            options={'verbose_name_plural': 'Acciones Pel\xedculas'},
        ),
        migrations.AlterModelOptions(
            name='accionpersona',
            options={'verbose_name_plural': 'Acciones Personas'},
        ),
        migrations.AlterModelOptions(
            name='accionserie',
            options={'verbose_name_plural': 'Acciones Series'},
        ),
        migrations.AlterModelOptions(
            name='coleccion',
            options={'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='contenidomultimedia',
            options={'verbose_name_plural': 'Contenidos Multimedia'},
        ),
    ]
