# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxfilm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='id_contenidoAPI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='id_contenidoAPI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contenidomultimedia',
            name='id_contenidoAPI',
            field=models.IntegerField(),
        ),
    ]
