BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXX XXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XX XXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXFFFFFFFFFFFFFFFF X FFFFFFFFFFXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXFFFFFFFFFFFFFFFFFXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        BB BBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXX
        BBBBB
        BBBBBB
      XXXXXX
      XXXX XXXXXXX XXXXXXXXXXXXXXX XXXXXX
        BBB BB BB BBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXFFFFFFFFFFFFFFFF X FFFFFFFFFFXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXFFFFFFFFFFFFFFFFFXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        BB BBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXX
        BBBBB
        BBBBBB
      XXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
        BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXFFFFFFFFFFFFFFFFXXXXX
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
                  XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                  XXXXX
                  BBB BBB BB BBBBBBBBBBBBBBBB
                  XXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXFFFFFFFFFFFFFFFFXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXX
                  BBBBBB
                XXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        BB BBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
        XXXXXXXXX
        BBBBB
        BBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB